"""
Template-based Snakefile generator (modernized for CLI).
"""

from textwrap import dedent
from snakebuilder.rules.registry import get_rule, select_ruleset


# ======================================================================
# HEADERS
# ======================================================================

HEADER_CORE = dedent("""
# ==========================================================
# 🧬 Auto-generated Snakemake workflow
# Generated by snakebuilder CLI
# ==========================================================

import os
from pathlib import Path
from snakemake.shell import shell
shell.executable("/bin/bash")

SAMPLES = list(config.get("samples", {}).keys())
THREADS = config.get("threads", 4)
MEMORY = config.get("memory", 4000)
RUN_DIR = Path(config.get("run_dir", "run_output")).resolve()

ALL_RULE_INPUTS = []

rule all:
        input: ALL_RULE_INPUTS
        run:
            pass
""")

# --------- Cloud header (minimal) ----------
HEADER_CLOUD = dedent("""
# ==========================================================
# 🧬 Auto-generated Snakemake workflow (Cloud mode)
# Generated by snakebuilder CLI
# ==========================================================

import os, sqlite3, json
from pathlib import Path
from snakemake.shell import shell
shell.executable("/bin/bash")

SAMPLES = list(config.get("samples", {}).keys())
THREADS = config.get("threads", 4)
MEMORY = config.get("memory", 4000)

RUN_DIR = Path(config.get("run_dir", "run_output")).resolve()
EXP_ID = RUN_DIR.parent.name
DATABASE_PATH = str(RUN_DIR.parents[2] / "circDB.db")

def update_step_status(experiment_id: int, step_name: str, new_status: str):
    conn = sqlite3.connect(DATABASE_PATH)
    cursor = conn.cursor()
    cursor.execute("SELECT step_statuses FROM experiments WHERE id = ?", (experiment_id,))
    row = cursor.fetchone()
    if not row:
        conn.close()
        raise ValueError(f"Experiment with ID {experiment_id} not found.")
    raw = row[0]
    try:
        statuses = json.loads(raw)
    except Exception:
        conn.close()
        raise ValueError("Invalid step_statuses JSON")
    updated = False
    for step in statuses:
        if step.get("step") == step_name:
            step["status"] = new_status
            updated = True
            break
    if not updated:
        conn.close()
        raise ValueError(f"Step '{step_name}' not found.")
    cursor.execute(
        "UPDATE experiments SET step_statuses=? WHERE id=?",
        (json.dumps(statuses), experiment_id)
    )
    conn.commit()
    conn.close()

# Only define list — NOT RULE ALL yet
ALL_RULE_INPUTS = []
""")

# ======================================================================
# CLOUD HEADER STEP BLOCKS
# ======================================================================

CLOUD_HEADER_STEP_BLOCKS = {
    "detect": dedent("""
# Detect
DETECT_CONFIG = config.get("detect", {})
DETECT_GTF = DETECT_CONFIG.get("gtf", "")
DETECT_FASTA = DETECT_CONFIG.get("fasta", "")
DETECT_OUTPUT = []
if DETECT_GTF and DETECT_FASTA:
    DETECT_OUTPUT = ["run_output/circtools_ci/CircRNACount"]
"""),

    "processing": dedent("""
# Alignment
ALIGN_OUTPUT = []
if SAMPLES:
    ALIGN_OUTPUT = expand("run_output/alignment/{sample}/{sample}_Aligned.out.sam", sample=SAMPLES)
"""),

    "nanopore": dedent("""
# Nanopore
NANO_CONFIG = config.get("nanopore", {})
NANOSAMPLES = list(NANO_CONFIG.get("samples", {}).keys())
NANO_GENOME = NANO_CONFIG.get("genome", "")
NANO_REF_DIR = NANO_CONFIG.get("reference_dir", "")
NANOPORE_OUTPUT = []
if NANOSAMPLES and NANO_GENOME and NANO_REF_DIR:
    NANOPORE_OUTPUT = expand("run_output/nanopore/{sample}.done", sample=NANOSAMPLES)
"""),

    "padlock": dedent("""
# Padlock
PADLOCK_CONFIG = config.get("padlock", {})
GENES = [PADLOCK_CONFIG.get("gene", "Slc8a1")]
GTF_PATH_FILE = PADLOCK_CONFIG.get("gtf", "")
FASTA_PATH_FILE = PADLOCK_CONFIG.get("fasta", "")
PREFIX_PATH_FILE = PADLOCK_CONFIG.get("prefix", "")
PADLOCK_OUTPUT = []
if GTF_PATH_FILE and FASTA_PATH_FILE and PREFIX_PATH_FILE:
    PADLOCK_OUTPUT = expand("run_output/padlock_output/{gene}_padlock_design_linear_FSJ.csv", gene=GENES)
"""),

    "conservation": dedent("""
# Conservation
CONSERVATION_CONFIG = config.get("conservation", {})
CONSERVATION_GTF = CONSERVATION_CONFIG.get("gtf", "")
CONSERVATION_FASTA = CONSERVATION_CONFIG.get("fasta", "")
CONSERVATION_PREFIX = CONSERVATION_CONFIG.get("prefix", "")
CONSERVATION_GENES = CONSERVATION_CONFIG.get("genes", [])
CONSERVATION_OUTPUT = []
if CONSERVATION_GTF and CONSERVATION_FASTA and CONSERVATION_PREFIX and CONSERVATION_GENES:
    CONSERVATION_OUTPUT = ["run_output/conservation_output/.done"]
"""),

    "enrichment": dedent("""
# Enrichment
ENRICHMENT_CONFIG = config.get("enrichment", {})
ENRICHMENT_GTF = ENRICHMENT_CONFIG.get("gtf", "")
ENRICHMENT_FASTA = ENRICHMENT_CONFIG.get("fasta", "")
ENRICHMENT_PREFIX = ENRICHMENT_CONFIG.get("prefix", "")
REPEATS = ENRICHMENT_CONFIG.get("repeats", [])
ENRICHMENT_OUTPUT = []
if ENRICHMENT_GTF and ENRICHMENT_FASTA and ENRICHMENT_PREFIX and REPEATS:
    ENRICHMENT_OUTPUT = expand("run_output/enrich/output/{repeat}_output_2000_iter.csv", repeat=REPEATS)
"""),

    "primer": dedent("""
# Primer
PRIMER_CONFIG = config.get("primer", {})
PRIMER_GENES = PRIMER_CONFIG.get("genes", [])
PRIMER_OUTPUT = []
if all(PRIMER_CONFIG.get(k) for k in ("gtf", "fasta", "genes", "prefix")):
    PRIMER_OUTPUT = expand("run_output/primer_output/{gene}_primer_report.html", gene=PRIMER_GENES)
"""),

    "circtest": dedent("""
# CircTest
CIRCTEST_CONFIG = config.get("circtest", {})
CIRCTEST_OUTPUT = []
if CIRCTEST_CONFIG.get("enabled", True) and \
   os.path.exists("run_output/circtools_ci/CircRNACount") and \
   os.path.exists("run_output/circtools_ci/LinearCount"):
    CIRCTEST_OUTPUT = ["run_output/circtest_output/.done"]
"""),

    "ciriquant": dedent("""
# CIRIquant
CIRIQUANT_OUTPUT = expand("run_output/ciriquant/{sample}/circ/{sample}.ciri", sample=SAMPLES)
"""),

    "metatool": dedent("""
# MetaTool
METATOOL_OUTPUT = []
if os.path.exists("run_output/circtools_ci/detect.done") and \
   all(os.path.exists(f"run_output/ciriquant/{s}/.done") for s in SAMPLES):
    METATOOL_OUTPUT = ["run_output/metatool/.metatool_done"]
"""),

    "sirna": dedent("""
# siRNA
SIRNA_CONF = config.get("sirna", {})
SIRNA_OUTPUT = []
if SIRNA_CONF.get("gtf") and SIRNA_CONF.get("fasta") and SIRNA_CONF.get("organism"):
    SIRNA_OUTPUT = ["run_output/sirna_output/.sirna_done"]
""")
}


# ======================================================================
# MAIN GENERATOR
# ======================================================================

def generate_snakefile(steps: list[str], use_cloud: bool = False) -> str:

    select_ruleset("cloud" if use_cloud else "core")
    header = HEADER_CLOUD if use_cloud else HEADER_CORE
    parts = [header]

    # Insert selected step output blocks
    if use_cloud:
        for step in steps:
            if step in CLOUD_HEADER_STEP_BLOCKS:
                parts.append(CLOUD_HEADER_STEP_BLOCKS[step])

        # Build accumulator block EXACTLY like original Python version
        acc = ["\n# Accumulate outputs\nALL_RULE_INPUTS = []\n"]

        if "detect" in steps:
            acc.append("if DETECT_OUTPUT:\n    ALL_RULE_INPUTS += DETECT_OUTPUT\n")
        if "processing" in steps:
            acc.append("if ALIGN_OUTPUT:\n    ALL_RULE_INPUTS += ALIGN_OUTPUT\n")
        if "padlock" in steps:
            acc.append("if PADLOCK_OUTPUT:\n    ALL_RULE_INPUTS += PADLOCK_OUTPUT\n")
        if "conservation" in steps:
            acc.append("if CONSERVATION_OUTPUT:\n    ALL_RULE_INPUTS += CONSERVATION_OUTPUT\n")
        if "enrichment" in steps:
            acc.append("if ENRICHMENT_OUTPUT:\n    ALL_RULE_INPUTS += ENRICHMENT_OUTPUT\n")
        if "primer" in steps:
            acc.append("if PRIMER_OUTPUT:\n    ALL_RULE_INPUTS += PRIMER_OUTPUT\n")
        if "circtest" in steps:
            acc.append("if CIRCTEST_OUTPUT:\n    ALL_RULE_INPUTS += CIRCTEST_OUTPUT\n")
        if "nanopore" in steps:
            acc.append("if NANOPORE_OUTPUT:\n    ALL_RULE_INPUTS += NANOPORE_OUTPUT\n")
        if "ciriquant" in steps:
            acc.append("if CIRIQUANT_OUTPUT:\n    ALL_RULE_INPUTS += CIRIQUANT_OUTPUT\n")
        if "metatool" in steps:
            acc.append("if METATOOL_OUTPUT:\n    ALL_RULE_INPUTS += METATOOL_OUTPUT\n")
        if "sirna" in steps:
            acc.append("if SIRNA_OUTPUT:\n    ALL_RULE_INPUTS += SIRNA_OUTPUT\n")

        parts.append("\n".join(acc))

        # Insert rule all BELOW accumulator, BEFORE rules
        parts.append(dedent("""
rule all:
    input:
        ALL_RULE_INPUTS
"""))

    # Append actual rules at end
    from snakebuilder.rules.registry import load_rules
    rules = load_rules()

    for step in steps:
        parts.append(f"\n# --- {step.upper()} ---")
        if step not in rules:
            parts.append(f"# ⚠ Rule '{step}' not found\n")
        else:
            parts.append(get_rule(step))

    return "\n".join(parts)
